name: Build docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'    
      - 'dockerfile'    
      - '.github/workflows/**' 

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'
      REPOSITORY_NAME: 'myprojectapi'
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Ensure the ECR repository exists
      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names ${{ env.REPOSITORY_NAME }} --region ${{ env.AWS_REGION }} 2>/dev/null || \
          aws ecr create-repository --repository-name ${{ env.REPOSITORY_NAME }} --region ${{ env.AWS_REGION }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-springboot-app:latest .

      # Tag the Docker image for ECR
      - name: Tag Docker image
        run: |
          caller=$(aws sts get-caller-identity --query 'Account' --output text)
          REPOSITORY_URI=$caller.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}
          IMAGE_TAG=$(echo ${{ env.IMAGE_TAG }} | head -c 7)
          docker tag my-springboot-app:latest $REPOSITORY_URI:$IMAGE_TAG
          docker tag my-springboot-app:latest $REPOSITORY_URI:latest

      # Push the Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          caller=$(aws sts get-caller-identity --query 'Account' --output text)
          REPOSITORY_URI=$caller.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}
          IMAGE_TAG=$(echo ${{ env.IMAGE_TAG }} | head -c 7)
          docker push $REPOSITORY_URI:$IMAGE_TAG
          docker push $REPOSITORY_URI:latest